/*
Cat as a service (CATAAS)

Testing SecurityAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package cataas

import (
	"context"
	openapiclient "github.com/mccallry/cataas-go-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_cataas_SecurityAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecurityAPIService ApiSecuritySignIn", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SecurityAPI.ApiSecuritySignIn(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecurityAPIService ApiSecuritySignUp", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SecurityAPI.ApiSecuritySignUp(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
