/*
Cat as a service (CATAAS)

Cat as a service (CATAAS) is a REST API to spread peace and love (or not) thanks to cats.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AdminCatsBrowse200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminCatsBrowse200ResponseInner{}

// AdminCatsBrowse200ResponseInner struct for AdminCatsBrowse200ResponseInner
type AdminCatsBrowse200ResponseInner struct {
	Id *string `json:"_id,omitempty"`
	Validated bool `json:"validated"`
	File string `json:"file"`
	Mimetype *string `json:"mimetype,omitempty"`
	Size *float32 `json:"size,omitempty"`
	Tags []string `json:"tags"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminCatsBrowse200ResponseInner AdminCatsBrowse200ResponseInner

// NewAdminCatsBrowse200ResponseInner instantiates a new AdminCatsBrowse200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminCatsBrowse200ResponseInner(validated bool, file string, tags []string) *AdminCatsBrowse200ResponseInner {
	this := AdminCatsBrowse200ResponseInner{}
	this.Validated = validated
	this.File = file
	this.Tags = tags
	return &this
}

// NewAdminCatsBrowse200ResponseInnerWithDefaults instantiates a new AdminCatsBrowse200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminCatsBrowse200ResponseInnerWithDefaults() *AdminCatsBrowse200ResponseInner {
	this := AdminCatsBrowse200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdminCatsBrowse200ResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdminCatsBrowse200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AdminCatsBrowse200ResponseInner) SetId(v string) {
	o.Id = &v
}

// GetValidated returns the Validated field value
func (o *AdminCatsBrowse200ResponseInner) GetValidated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Validated
}

// GetValidatedOk returns a tuple with the Validated field value
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetValidatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Validated, true
}

// SetValidated sets field value
func (o *AdminCatsBrowse200ResponseInner) SetValidated(v bool) {
	o.Validated = v
}

// GetFile returns the File field value
func (o *AdminCatsBrowse200ResponseInner) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *AdminCatsBrowse200ResponseInner) SetFile(v string) {
	o.File = v
}

// GetMimetype returns the Mimetype field value if set, zero value otherwise.
func (o *AdminCatsBrowse200ResponseInner) GetMimetype() string {
	if o == nil || IsNil(o.Mimetype) {
		var ret string
		return ret
	}
	return *o.Mimetype
}

// GetMimetypeOk returns a tuple with the Mimetype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetMimetypeOk() (*string, bool) {
	if o == nil || IsNil(o.Mimetype) {
		return nil, false
	}
	return o.Mimetype, true
}

// HasMimetype returns a boolean if a field has been set.
func (o *AdminCatsBrowse200ResponseInner) HasMimetype() bool {
	if o != nil && !IsNil(o.Mimetype) {
		return true
	}

	return false
}

// SetMimetype gets a reference to the given string and assigns it to the Mimetype field.
func (o *AdminCatsBrowse200ResponseInner) SetMimetype(v string) {
	o.Mimetype = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *AdminCatsBrowse200ResponseInner) GetSize() float32 {
	if o == nil || IsNil(o.Size) {
		var ret float32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *AdminCatsBrowse200ResponseInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given float32 and assigns it to the Size field.
func (o *AdminCatsBrowse200ResponseInner) SetSize(v float32) {
	o.Size = &v
}

// GetTags returns the Tags field value
func (o *AdminCatsBrowse200ResponseInner) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *AdminCatsBrowse200ResponseInner) SetTags(v []string) {
	o.Tags = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AdminCatsBrowse200ResponseInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AdminCatsBrowse200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AdminCatsBrowse200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AdminCatsBrowse200ResponseInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminCatsBrowse200ResponseInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AdminCatsBrowse200ResponseInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AdminCatsBrowse200ResponseInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o AdminCatsBrowse200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminCatsBrowse200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	toSerialize["validated"] = o.Validated
	toSerialize["file"] = o.File
	if !IsNil(o.Mimetype) {
		toSerialize["mimetype"] = o.Mimetype
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	toSerialize["tags"] = o.Tags
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminCatsBrowse200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validated",
		"file",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminCatsBrowse200ResponseInner := _AdminCatsBrowse200ResponseInner{}

	err = json.Unmarshal(data, &varAdminCatsBrowse200ResponseInner)

	if err != nil {
		return err
	}

	*o = AdminCatsBrowse200ResponseInner(varAdminCatsBrowse200ResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "_id")
		delete(additionalProperties, "validated")
		delete(additionalProperties, "file")
		delete(additionalProperties, "mimetype")
		delete(additionalProperties, "size")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminCatsBrowse200ResponseInner struct {
	value *AdminCatsBrowse200ResponseInner
	isSet bool
}

func (v NullableAdminCatsBrowse200ResponseInner) Get() *AdminCatsBrowse200ResponseInner {
	return v.value
}

func (v *NullableAdminCatsBrowse200ResponseInner) Set(val *AdminCatsBrowse200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminCatsBrowse200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminCatsBrowse200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminCatsBrowse200ResponseInner(val *AdminCatsBrowse200ResponseInner) *NullableAdminCatsBrowse200ResponseInner {
	return &NullableAdminCatsBrowse200ResponseInner{value: val, isSet: true}
}

func (v NullableAdminCatsBrowse200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminCatsBrowse200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


