name: Create Tag

on:
  workflow_dispatch:

env:
  FOLDER_NAME: "openapi"
  FILE_NAME: "cataas"

permissions: write-all

jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get OpenAPI Version
    outputs:
      FILE_VERSION: ${{ steps.get-package-version.outputs.FILE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Package Version
        id: get-package-version
        run: echo "FILE_VERSION=$(jq .info.version ./${{ env.FOLDER_NAME }}/${{ env.FILE_NAME }}.json)" >> $GITHUB_OUTPUT
  create-tag:
    runs-on: ubuntu-latest
    name: Create Tag
    needs: get-version
    steps:
      - name: Echo ENV
        run: echo ${{ needs.get-version.outputs.FILE_VERSION }}