name: Create Tag

on:
  workflow_dispatch:

env:
  FOLDER_NAME: "openapi"
  FILE_NAME: "cataas"
  FILE_VERSION: "0.0.0"

permissions: write-all

jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get OpenAPI Version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Package Version
        run: echo "FILE_VERSION=$(jq .info.version ./${{ env.FOLDER_NAME }}/${{ env.FILE_NAME }}.json)" >> $GITHUB_ENV
      - name: Echo ENV
        run: echo $FILE_VERSION
  create-tag:
    runs-on: ubuntu-latest
    name: Create Tag
    needs: get-version
    steps:
      - name: Echo ENV
        run: echo $FILE_VERSION