name: Create Tag

on:
  workflow_dispatch:

env:
  FOLDER_NAME: "openapi"
  FILE_NAME: "cataas"

permissions: write-all

jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get OpenAPI Version
    outputs:
      FILE_VERSION: ${{ steps.get-package-version.outputs.FILE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Package Version
        id: get-package-version
        run: echo "FILE_VERSION=$(jq -r .info.version ./${{ env.FOLDER_NAME }}/${{ env.FILE_NAME }}.json)" >> $GITHUB_OUTPUT
  create-tag:
    runs-on: ubuntu-latest
    name: Create Tag
    needs: get-version
    steps:
      - name: Create GitHub Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ needs.get-version.outputs.FILE_VERSION }}',
              sha: context.sha
            })
  goreleaser:
    runs-on: ubuntu-latest
    name: Go Release
    needs: create-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}