name: Generate Go SDK

on:
  push:
    branches: [ "main" ]
    paths: [ "openapi/**.json" ]
  workflow_dispatch:

env:
  FOLDER_NAME: "openapi"
  FILE_NAME: "cataas"
  USER_ID: "mccallry"
  REPO_ID: "cataas-go-sdk"
  GEN_DIR: go-client
  GO_VERSION: 1.18.0

permissions: write-all

jobs:
  json-to-yaml:
    runs-on: ubuntu-latest
    name: Convert JSON to YAML
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate YAML Output
        uses: fabasoad/data-format-converter-action@v0
        id: json2yaml
        with:
          input: "${{ env.FOLDER_NAME }}/${{ env.FILE_NAME }}.json"
          from: "json"
          to: "yaml"
      - name: Save YAML to File
        run: |
          echo "${{ steps.json2yaml.outputs.output }}" > "${{ env.FOLDER_NAME }}/${{ env.FILE_NAME }}.yaml"
      - name: Commit Updated YAML File
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          default_author: github_actions
          message: "Update YAML File"
  generate-sdk:
    runs-on: ubuntu-latest
    name: Generate Go SDK
    needs: json-to-yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add Go to ENV
        uses: actions/setup-go@v5
        with:
          go-version: ">=${{ env.GO_VERSION }}"
      - name: Generate Go Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: go
          openapi-file: "${{ env.FOLDER_NAME }}/${{ env.FILE_NAME }}.yaml"
          command-args: "-o ./${{ env.GEN_DIR }} -p enumClassPrefix=true -p disallowAdditionalPropertiesIfNotPresent=false --git-user-id ${{ env.USER_ID }} --git-repo-id ${{ env.REPO_ID }}"
      - name: Move Generated Files
        run: |
          rm -rf ./api ./docs ./test
          mv -vf ./${{ env.GEN_DIR }}/README.md ./README.GEN.md
          mv -vf ./${{ env.GEN_DIR }}/* ./
      - name: Go Tidy
        run: go mod tidy
      - name: Format Go Code
        run: gofmt -w -s .
      - name: Commit Generated SDK Files
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          default_author: github_actions
          message: "Update Go SDK"